[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/football-data/*"
  to = "https://api.football-data.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
